// Generated by https://quicktype.io
export interface Data {
    id:      string;
    month:   string;
    camp:    string;
    country: string;
    school:  string;
    lessons?: number;
    totalMonthLesson?: number
}

export interface LookUp {
    id: number; text: string;
}